apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: anqpmd7cz-python
  janus-idp.io/tekton: anqpmd7cz-python
  backstage.io/kubernetes-id: anqpmd7cz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: anqpmd7cz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
