apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: anqpmd7cz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anqpmd7cz-python 
  name: anqpmd7cz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: anqpmd7cz-python 
